INSERT INTO players (id, name, score, description, image, position, wins, losses, draws) VALUES
('1', 'Calesita Fornarini', 90, 'El 10 del equipo, poca visión de juego pero buena pegada. Mínimo apoyo defensivo.', '/players/calesita.png', 'Delantero', 0, 0, 0),
('2', 'El mágico Maggio', 52, 'Olfato goleador infalible y padre responsable.', '/players/maggio.png', 'Mediocampista', 0, 0, 0),
('3', 'Eze Barros', 68, 'No pasa nadie por su lado. Un candado.', '/players/barros.png', 'Defensor', 0, 0, 0),
('4', 'Balonchad', 74, 'Reflejos felinos bajo los tres palos.', '/players/balonchad.png', 'Arquero', 0, 0, 0),
('5', 'El Fabri', 70, 'La pausa necesaria para oxigenar el juego. Padre de una bendición.', '/players/fabri.png', 'Delantero', 0, 0, 0),
('6', 'Agus', 69, 'Distribuye el juego con precisión milimétrica.', '/players/agus.png', 'Mediocampista', 0, 0, 0),
('7', 'TEFO', 73, 'Velocidad pura por la banda. Marcaje asfixiante sobre el rival.', '/players/tefo.jpg', 'Mediocampista', 0, 0, 0),
('8', 'El tanque Ferronato', 66, 'Liderazgo y entrega total los 90 minutos. Actualmente lesionado.', '/players/ferronato.png', 'Defensor', 0, 0, 0),
('9', 'Leo el pulpo Tricerri', 92, 'Regates imposibles en espacios reducidos. Jugador de toda la cancha', '/players/tricerri.jpg', 'Todoterreno', 0, 0, 0),
('10', 'Nando', 50, 'Firmeza absoluta en la última línea.', '/players/nando.png', 'Defensor', 0, 0, 0),
('11', 'Juli', 70, 'Ataques punzantes y directos. Especialista de los tres dedos.', '/players/juli.png', 'Mediocampista', 0, 0, 0),
('12', 'Tiago', 80, 'Mindfulness, meditación y terapia. Jugador de pádel.', '/players/tiago.png', 'Mediocampista', 0, 0, 0),
('13', 'Mazzini (zurdo)', 75, 'Temperamental. Imponente presencia física.', '/players/mazzini.png', 'Defensor', 0, 0, 0),
('14', 'Luchini', 79, 'Poeta de la redonda. Filigranas y regates renacentistas. Definición en blanco y negro.', '/players/luchini.jpg', 'Mediocampista', 0, 0, 0),
('15', 'Nico Dalmás', 80, 'Lucha cada balón como si fuera el último.', 'https://images.unsplash.com/photo-1575361204480-aadea25e6e68?q=80&w=2671&auto=format&fit=crop', 'Defensor', 0, 0, 0),
('16', 'Maxi el amigo de leo', 60, 'La pausa necesaria para oxigenar el juego.', 'https://images.unsplash.com/photo-1575361204480-aadea25e6e68?q=80&w=2671&auto=format&fit=crop', 'Mediocampista', 0, 0, 0),
('17', 'El bodi', 80, 'Especialista en jugar de delantero los ultimos veinte minutos y perder el partido', '/players/bodi.png', 'Defensor', 0, 0, 0),
('18', 'Maurito ecloud', 75, 'Playmaker. El cerebro.Tristemente influenciado por el fútbol español.', '/players/maurito.png', 'Mediocampista', 0, 0, 0),
('19', 'Tincho Stefoni', 75, 'Actualmente fuera de las canchas.', 'https://images.unsplash.com/photo-1575361204480-aadea25e6e68?q=80&w=2671&auto=format&fit=crop', 'Defensor', 0, 0, 0),
('20', 'EL GALLE', 50, 'Firmeza absoluta en la última línea.', 'https://images.unsplash.com/photo-1575361204480-aadea25e6e68?q=80&w=2671&auto=format&fit=crop', 'Defensor', 0, 0, 0);
